<a href="https://colab.research.google.com/github/Saulrega/pytorch/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
A = torch.randn((8,3,5))

In [ ]:
A.size()

torch.Size([8, 3, 5])

In [ ]:
# Establecer tipo por defecto:

# torch.set_default_tensor_type('torch.FloatTensor') #torch.float32
# torch.set_default_tensor_type('torch.DoubleTensor') #torch.float64

In [ ]:
A.size() == (8,3,5)

True

In [ ]:
A[0][0][0]
A[0,0,0]

tensor(0.2680)

In [ ]:
A[0,0,:]
A[0,:,0]

tensor([ 0.2680, -2.0276, -0.5462])

In [ ]:
C = torch.zeros((5,5))

In [ ]:
C.dtype

torch.float32

In [ ]:
D = torch.randint(2,(5,5))

In [ ]:
D

tensor([[0, 0, 0, 1, 0],
        [0, 0, 1, 1, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0]])

In [ ]:
D.dtype

torch.int64

In [ ]:
C + D

tensor([[0., 0., 0., 1., 0.],
        [0., 0., 1., 1., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.]])

In [ ]:
torch.set_default_tensor_type('torch.FloatTensor') #torch.float32

In [ ]:
C.device

device(type='cpu')

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
x = torch.rand(3,5) #cpu
y = torch.ones_like(x, device=device) #gpu

In [ ]:
x = x.to(device) #gpu

In [ ]:
print(x)
print(x.cpu())

tensor([[0.7281, 0.2031, 0.8471, 0.6128, 0.7518],
        [0.2908, 0.0817, 0.7002, 0.0921, 0.5596],
        [0.7579, 0.5891, 0.0333, 0.2609, 0.2861]])
tensor([[0.7281, 0.2031, 0.8471, 0.6128, 0.7518],
        [0.2908, 0.0817, 0.7002, 0.0921, 0.5596],
        [0.7579, 0.5891, 0.0333, 0.2609, 0.2861]])


In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
%cd 'Deep learning pytorch'
!ls  

/content/drive/MyDrive/Colab Notebooks/Deep learning pytorch
 dl-pytorch  'Setup inicial.ipynb'   Tensores.ipynb


In [ ]:
from torchvision import datasets

In [ ]:
dir(datasets)

In [ ]:
cifar = datasets.CIFAR10('/content/drive/MyDrive/Colab Notebooks/Deep learning pytorch/dl-pytorch/datasets', download=True)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting /content/drive/MyDrive/Colab Notebooks/Deep learning pytorch/dl-pytorch/datasets/cifar-10-python.tar.gz to /content/drive/MyDrive/Colab Notebooks/Deep learning pytorch/dl-pytorch/datasets


In [ ]:
len(cifar)

50000

In [ ]:
data = torch.Tensor(cifar.data)

In [ ]:
data.size()

torch.Size([50000, 32, 32, 3])